apiVersion: v1
kind: Service
metadata:
  name: sensor-service
  namespace: industrial-iot
spec:
  type: NodePort # Permet d'accéder au service depuis l'extérieur du cluster
  selector:
    app: sensor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30001 # On force le port 30001
